# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d1658fcebcf14df076dee5f34abdc1649e764e941b9ef140d7b0154f8898869fdc7a7512a808a42b22db204c130c8b11108a604505c8d6d162c4330e4735d9

test:
  secret_key_base: 7fa329a2680b072d6793f73ac8d4fc92dfe80b226b3f67d0d9206c9cd487c9ba67c239703c755f3959f209202aac0167e6e980ee2df05729e32d676d878279a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
